name: DotNet Publish

on:
 push:
    branches: [ main ]
    paths:
      - frontend/**
      - .github/workflows/dotnet*

jobs:
  Build_Publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      working-directory: ./frontend
      run: docker build -t springting-frontend:dev-latest .

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2 

    # - name: Docker Push
    #   run: docker push bla bla 