name: DotNet Publish

on:
 push:
    # branches: [ main ]
    branches: [ '**' ]
    paths:
      - frontend/**
      - .github/workflows/dotnet**      

jobs:
  Build_Publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      working-directory: ./frontend
      run: docker build -t springting-frontend:dev-latest .

    # - name: Docker Push
    #   run: docker push bla bla 