
name: Maven Build and Test

on:
 push:
    branches: [ '**' ]
    branches-ignore:
      - "main"    
    paths:
      - backend/**
      - .github/workflows/maven*

jobs:
  Build_Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      working-directory: ./backend
      run: mvn -B package --file pom.xml 
