name: Terraform validate

on:
 push:
    # branches: [ main ]
    branches: [ '**' ]
    paths:
      - terraform/**
      - .github/workflows/terraform*

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -diff -recursive
        working-directory: terraform/
